name: Python Package using Conda
on:
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: List files in current directory
      run: cd $CONDA/bin && ls
    - name: Create environment
      run: |
        $CONDA/bin/conda create -y --name hawker python=3.7
    - name: Activate environment
      run: |
        $CONDA/bin/activate hawker
    - name: Install libraries in environment
      run: |
        pip install python-telegram-bot --upgrade
        pip install geopy
        pip install fuzzywuzzy
        $CONDA/bin/conda install geopandas -y
    - name: Run py files to update data files
      run: |
        $CONDA/bin/python data_utils.py
        $CONDA/bin/python mrt_hawker_dist.py
    
    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time
      
    - name: Git config
      run: |
        git config user.name darensin01
        git config user.email darensin01@gmail.com
        
    - name: Git add, commit, push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "${{ steps.current-time.outputs.time }}: new data pushed"
